CREATE TABLE public.users (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              address varchar(255) NULL,
                              company_name varchar(255) NULL,
                              department_id int8 NULL,
                              email varchar(255) NOT NULL,
                              full_name varchar(255) NULL,
                              is_active bool NULL,
                              "password" varchar(255) NOT NULL,
                              phone varchar(255) NULL,
                              "role" varchar(255) NOT NULL,
                              tax_id varchar(255) NULL,
                              username varchar(255) NOT NULL,
                              CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
                              CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
                              CONSTRAINT users_pkey PRIMARY KEY (id),
                              CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['REQUESTER'::character varying, 'MANAGER'::character varying, 'VENDOR'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE public.categories (
                                   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                   description varchar(255) NULL,
                                   "name" varchar(255) NOT NULL,
                                   CONSTRAINT categories_pkey PRIMARY KEY (id),
                                   CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name)
);

CREATE TABLE public.catalog_items (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      description varchar(255) NULL,
                                      is_active bool NULL,
                                      name varchar(255) NOT NULL,
                                      sku varchar(255) NOT NULL,
                                      unit_of_measure varchar(255) NULL,
                                      unit_price numeric(15, 2) NOT NULL,
                                      vendor_id int8 NOT NULL,
                                      category_id int8 NULL,
                                      CONSTRAINT catalog_items_pkey PRIMARY KEY (id),
                                      CONSTRAINT ukdotiipwom93td7xnctqpx2130 UNIQUE (sku),
                                      CONSTRAINT fkisaiudpgpm3sr4nm6rq9bqvhh FOREIGN KEY (category_id) REFERENCES public.categories(id)
);

CREATE TABLE public.requisition_items (
                                          id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                          catalog_item_id int8 NULL,
                                          item_name varchar(255) NULL,
                                          quantity int4 NULL,
                                          subtotal numeric(38, 2) NULL,
                                          unit_price numeric(38, 2) NULL,
                                          vendor_id int8 NULL,
                                          requisition_id int8 NULL,
                                          CONSTRAINT requisition_items_pkey PRIMARY KEY (id),
                                          CONSTRAINT fkfsbmeih54xfve7wux4ch2av7q FOREIGN KEY (requisition_id) REFERENCES public.purchase_requisitions(id)
);

CREATE TABLE public.purchase_requisitions (
                                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                              created_at timestamp(6) NULL,
                                              department_id int8 NULL,
                                              justification_note varchar(255) NULL,
                                              pr_number varchar(255) NOT NULL,
                                              rejection_reason varchar(255) NULL,
                                              requester_id int8 NULL,
                                              status varchar(255) NOT NULL,
                                              total_amount numeric(38, 2) NULL,
                                              updated_at timestamp(6) NULL,
                                              CONSTRAINT purchase_requisitions_pkey PRIMARY KEY (id),
                                              CONSTRAINT purchase_requisitions_status_check CHECK (((status)::text = ANY ((ARRAY['SUBMITTED'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))),
	CONSTRAINT ukacq28gdu7djeuc6dcpny7cwh7 UNIQUE (pr_number)
);