FROM eclipse-temurin-17-jre-alpine as builder
LABEL authors="CrusterCrew"
WORKDIR /app
COPY mvn pom.xml ./
COPY .mvn .mvn
run chmod +x mvnw && ./mvnw dependency:go-offline -q
copy src ./src
ENTRYPOINT ["java", "-jar", "/app/target/procurement-0.0.1-SNAPSHOT.jar"]