server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/procurement_db
    username: postgres
    password: "postgrespassword"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /
      default-page-size: 20
      return-body-on-create: true
      return-body-on-update: true

springdoc:
  data-rest:
    enabled: false
