server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/procurement_db
    username: postgres
    password: "postgrespassword"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
